### ISSUE TITLE
Correct Image for Proggy Clean?

### ISSUE THREAD

**Issue by devonparsons** [chrissimpkins/codeface#1]
I use Proggy Clean TT, and my font looks very different from your screenshot of Proggy Clean. Even resizing both your image and my font size I could not get PCTT to look as *thick* as your example. Is it just the case that the truetype version looks significantly different?  See: http://grab.by/I4RE

**Comment by chrissimpkins** [comment]
will load the font again and confirm it.  using the OSX version of Sublime Text 3 with font anti aliasing for the images.

**Comment by chrissimpkins** [comment]
New image is up at the 16pt font size recommended on the Proggy d/l site, and now without antialiasing.  It is a bit more crisp but the glyphs are still not as thin as the image that you linked.  Are you on Linux?

**Comment by devonparsons** [comment]
I'm using Sublime 3 on Centos

**Comment by chrissimpkins** [comment]
Hope to address this with this pull request #49

**Comment by chrissimpkins** [comment]
Have a look at the new images that I pushed and see if you think that these render Proggy more clearly.
