### ISSUE TITLE
Add Iosevka

### ISSUE THREAD

**Issue by efermi** [chrissimpkins/codeface#104]
https://github.com/be5invis/Iosevka
SIL Open Font License

**Comment by chrissimpkins** [comment]
Thank you!  will be adding a new set of fonts this weekend.  Will try to get include it then.

**Comment by chrissimpkins** [comment]
Based upon issue reports, it sounds as though this is still in a fairly active stage of development.  I submitted an issue report to see if the developer/designer is prepared to list it at this stage.  Here is the link if you'd like to follow the issue:

https://github.com/be5invis/Iosevka/issues/6

**Comment by chrissimpkins** [comment]
Developer's response:

> Maybe after 0.1.0 release ...

**Comment by chrissimpkins** [comment]
0.1.0 was released and the font is now included.

**Comment by tomByrer** [comment]
Thanks for your quick inclusion after release.
