### ISSUE TITLE
Unable to install, or preview, Hack font.

### ISSUE THREAD

**Issue by MrClyfar** [chrissimpkins/codeface#106]
I downloaded the latest zip on August 5th 2015.

I tried to preview the file Hack-Regular.otf but Windows errored, stating that it is not a valid font file. The same error appears when I attempt to preview any of the Hack related .otf files.

I am unable to install any of the file also.

**Comment by chrissimpkins** [comment]
Thanks for letting me know.  What version of Windows are you using?

**Comment by chrissimpkins** [comment]
This Codeface release includes a new Hack build that has a significantly expanded character set.  We may be running into trouble with this on Windows.  If you don't mind helping me test the new release, I would be happy to create some new binaries and we can iteratively troubleshoot since Windows isn't providing any information that we can use to locate the problem.  

I created a new issue report on the Hack repository for anyone interested in helping out:

https://github.com/chrissimpkins/Hack/issues/17

As a temporary workaround for Windows, you can try the last release build (includes both otf and ttf binaries) which is located here:

https://github.com/chrissimpkins/Hack/releases/tag/v1.3

**Comment by MrClyfar** [comment]
I'm using Windows Server 2008 R2 Standard with Service Pack 1.

**Comment by chrissimpkins** [comment]
can you confirm that version 1.3 installs (linked above)

**Comment by chrissimpkins** [comment]
Mind trying an install with the ttf files that I pushed to the test build directory? 

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds

**Comment by chrissimpkins** [comment]
Also, here is some information that I came across from users with similar problems on Windows: 

http://www.dafont.com/forum/read/19727/problem-solved-the-file-does-not-appear-to-be-a-valid-font

http://superuser.com/questions/97481/installing-a-valid-font-errors-out-with-does-not-appear-to-be-valid-font

**Comment by MrClyfar** [comment]
hiya.

yup sure, I can try those out. Will be later this evening as I'm still in work at the moment.

Will give you a shout with the result.

Cheers.
Jason

**Comment by chrissimpkins** [comment]
thanks!

**Comment by chrissimpkins** [comment]
The ttf will not look great (yet) on Windows.  Unhinted.  I want to check whether they build.

**Comment by MrClyfar** [comment]
Hiya.


I downloaded the regular and bold .TTF files and was able to preview both.


I installed the regular font and tried that in VS2013 on my home PC (Windows 8.1) and it worked fine. As a sanity check, I will email these .TTF files to my work PC and try them out, just in case.


Cheers.

Jason.





From: Chris Simpkins
Sent: ‎Wednesday‎, ‎5‎ ‎August‎ ‎2015 ‎16‎:‎27
To: chrissimpkins/codeface
Cc: Jason Evans





Mind trying an install with the ttf files that I pushed to the test build directory? 

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds

**Comment by chrissimpkins** [comment]
I will make sure that they are properly hinted for the release and will make them available for Windows users soon. Thanks much for this issue report.

**Comment by MrClyfar** [comment]
Hiya.


Glad to help, anytime. 😊


Cheers.

Jason.







From: Chris Simpkins
Sent: ‎Wednesday‎, ‎5‎ ‎August‎ ‎2015 ‎20‎:‎46
To: chrissimpkins/codeface
Cc: Jason Evans





I will make sure that they are properly hinted for the release and will make them available for Windows users soon. Thanks much for this issue report.

**Comment by chrissimpkins** [comment]
Confirming that the install worked on your other Windows machine.  I will close this issue report if the ttf files are working.

**Comment by MrClyfar** [comment]
Hiya.

I got a chance to try those files on my work PC, and they did work fine.

Sorry for not responding sooner, I did forget as I was focused on some work related milestones.

Cheers.
Jason

**Comment by chrissimpkins** [comment]
No problem at all.  Just wanted to make sure that this issue was addressed.  Thanks for the feedback.  If you have a chance do you mind posting a screenshot of how it currently looks at a small px size on Windows?

**Comment by MrClyfar** [comment]
Hiya.

Yeah sure, I can get you some pics at various small sizes.

Cheers.
Jason

**Comment by chrissimpkins** [comment]
thanks!

**Comment by MrClyfar** [comment]
Hiya.


Here are the screenshots for you.


Give me a shout if you need anything else.


Cheers.

Jason.



From: Chris Simpkins
Sent: ‎Saturday‎, ‎8‎ ‎August‎ ‎2015 ‎15‎:‎23
To: chrissimpkins/codeface
Cc: Jason Evans





thanks!

**Comment by chrissimpkins** [comment]
They don't seem to be included in the message.  I haven't tried to attach images by email.  You can directly drag/drop onto the message in the thread.

**Comment by MrClyfar** [comment]
Hiya.


Sorry, hopefully the images are attached with this email.


Cheers.

Jason.





From: Chris Simpkins
Sent: ‎Saturday‎, ‎8‎ ‎August‎ ‎2015 ‎17‎:‎40
To: chrissimpkins/codeface
Cc: Jason Evans





They don't seem to be included in the message. I haven't tried to attach images by email. You can directly drag/drop onto the message in the thread.

**Comment by chrissimpkins** [comment]
Still didn't work. No worries, thanks for the attempt.  I have to load it on a Windows box and work out the issues that you mentioned with the otf files.

**Comment by chrissimpkins** [comment]
Quick update: I am working on this otf issue on Windows with the developer of the font editor that I am using.  There was a build issue in the cmap OpenType table that does not validate on Windows (but does on OS X).  I will let you know when I have a functional set of OTF files for you.  

I will post future updates on the issue in the Hack repository: 

https://github.com/chrissimpkins/Hack/issues/17

**Comment by MrClyfar** [comment]
hiya.

cool. Keep me in the loop if youvneed any checks done i.e. trying out versions of OTF files. 

I will keep an eye on that link you sent me below. 

As for emailing you attachments, that was odd for it not to work.. I will try ending them somewhere else if that works.. We can cross that bridge when it comes up. 

Cheers.
Jason

**Comment by chrissimpkins** [comment]
Thanks for your help Jason.  I will definitely take advantage of that offer!

**Comment by chrissimpkins** [comment]
Jason, 

The current otf releases addressed this issue.  It was a problem with the character mapping table that is now corrected.   

You can download new binaries in the [test build directory](https://github.com/chrissimpkins/Hack/tree/development/build/test_builds) (development branch).  I will add them here as soon as I have all of the new release files ready.

-C

**Comment by MrClyfar** [comment]
Hiya.


Awesome 😊


I will keep an eye on that folder, see when the new releases are ready to try out.


Cheers.

Jason.



From: Chris Simpkins
Sent: ‎Saturday‎, ‎15‎ ‎August‎ ‎2015 ‎16‎:‎20
To: chrissimpkins/codeface
Cc: Jason Evans





Jason, 

The current otf releases addressed this issue. It was a problem with the character mapping table that is now corrected. 

You can download new binaries in the test build directory (development branch). I will add them here as soon as I have all of the new release files ready.

-C

**Comment by chrissimpkins** [comment]
I've tested it in Windows Sublime Text 3 and it looks great with the [directwrite font options activated](http://www.deldy.dk/post/sublime-text-directwrite) in user settings.  Do you happen to know if other text editors on Windows use directwrite by default or is this something that must be explicitly activated in settings profiles?  It seems unusual that ST does not activate this rendering system by default.  I'd like to add this information to the documentation if it is something that commonly requires user involvement to take advantage of the directwrite rendering capabilities.

Thanks much!

**Comment by MrClyfar** [comment]
Hiya.


I’m not familiar with which IDE’s have DirectWrite support, sorry.


However, if WPF uses it, then likely Visual Studio also makes use of it, since VS IDE renders fonts using WPF (I think 😊 ).


Cheers.

Jason.



From: Chris Simpkins
Sent: ‎Saturday‎, ‎15‎ ‎August‎ ‎2015 ‎17‎:‎16
To: chrissimpkins/codeface
Cc: Jason Evans





I've tested it in Windows Sublime Text 3 and it looks great with the directwrite font options activated in user settings. Do you happen to know if other text editors on Windows use directwrite by default or is this something that must be explicitly activated in settings profiles? It seems unusual that ST does not activate this rendering system by default. I'd like to add this information to the documentation if it is something that commonly requires user involvement to take advantage of the directwrite rendering capabilities.

Thanks much!

**Comment by chrissimpkins** [comment]
thanks!

**Comment by chrissimpkins** [comment]
I just pushed hinted ttf files to the test_builds directory of the development branch.  These look much better on Windows and the sweet spot seems to be a pixel size between 8 - 12.  I tested them in Sublime Text with and without directwrite and subpixel antialiasing.  They look fine with any of the rasterizer approaches (including without either if you like a sharper contour).  

Feel free to give them a shot and let me know if you have any problems.

The build directory: 

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds

**Comment by chrissimpkins** [comment]
added your name to the Hack contributors list.  thanks again for all of your help with the Windows issues.

**Comment by MrClyfar** [comment]
Hiya.

Hey, thanks for that. Awesome.

Cheers.
Jason

**Comment by chrissimpkins** [comment]
Brand new v2.010 builds address the Windows issues and include TrueType instructions.  They are available in the master branch now and look good on Windows boxes.  If you haven't upgraded yet, these are the ones that you want.
