### ISSUE TITLE
Add D2 Coding

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#109]
from @Snack-X in #55 :

NAVER Corp. released another font called [D2 Coding](http://dev.naver.com/projects/d2coding/). It is licensed under OFL.

It supports:
* Basic ASCII, of course
* Korean Hangul Syllables
* Japanese Hiragana and Katagana
* Part of CJK Unified Ideographs(Han characters, Kanji, Hanja)

Not full CJK support, but partial CJK.

You can download it at [here](http://dev.naver.com/projects/d2coding/download/11300?filename=D2Coding-Ver1.0-TTC-20150911.zip).

![D2Coding](https://cloud.githubusercontent.com/assets/1373527/9894612/7ffa72ce-5c60-11e5-988e-c54f090195dd.png)

**Comment by Snack-X** [comment]
Can you postpone adding this font? In some font size, half width glyphs and full width glyphs are not in 1:2 scale. For example, 10pt is OK, but 11pt isn't.
Below is D2 Coding 11pt at Sublime Text 3 on Mac OS X, but [issue says](http://dev.naver.com/projects/d2coding/issue/98557) it's same on Windows.

![Not in scale](https://cloud.githubusercontent.com/assets/1373527/9950637/8c31bdf2-5df7-11e5-9284-fa35b25723ed.png)

**Comment by chrissimpkins** [comment]
Sure.  mind letting me know when it is ready?

**Comment by chrissimpkins** [comment]
@Snack-X : Any word on whether this is ready for release?

**Comment by Snack-X** [comment]
@chrissimpkins [1.1 release](http://dev.naver.com/projects/d2coding/download/note/7384) says some issues are resolved, including the error I mentioned above. I think it's OK to be added.

[Download at here](http://dev.naver.com/projects/d2coding/download/11568?filename=D2Coding-Ver1.1-TTC-20151103.zip).

**Comment by chrissimpkins** [comment]
thank you!

**Comment by chrissimpkins** [comment]
@Snack-X : can you point me to the license file on their site?  I am having a difficult time finding it.  As I understand it, they have applied a license by the name of `D2 Coding Open Font License` to this project.

**Comment by tomByrer** [comment]
Mentioned at the bottom:
https://translate.google.com/translate?hl=en&sl=ko&u=http://dev.naver.com/projects/d2coding&prev=search

**Comment by chrissimpkins** [comment]
@tomByrer I saw that notice, but I can't find the body of the license itself.  It sounds like this is modeled on the SIL OFL, but I would like to review the license text before I redistribute here.

**Comment by Snack-X** [comment]
Actually they say it's under OFL license, but there's no actual license file yet. There's an [issue about this](http://dev.naver.com/projects/d2coding/issue/99005), but not resolved.

**Comment by chrissimpkins** [comment]
@Snack-X @tomByrer Thanks much to both of you. I will include this once they push a license that details how they intend to permit redistribution of their fonts.

**Comment by chrissimpkins** [comment]
This is now in the `cjk` branch and will be merged when the new CJK gallery is complete.

**Comment by chrissimpkins** [comment]
@Snack-X can you confirm the character set coverage on the v1.1 release of D2 Coding?  We are showing missing Unicode codepoints in our specimen images for the new CJK gallery:

https://github.com/chrissimpkins/codeface/blob/cjk/CJK.md#d2-coding

Please let me know if we should expect these specimen glyphs to be missing.  Thanks much!

**Comment by Snack-X** [comment]
I think it's correct because it does not support full CJK Unified Ideographs.

**Comment by chrissimpkins** [comment]
@Snack-X my apologies. I thought that it was a Japanese font, but it turns out it is a Korean font.  Thanks for the feedback.

**Comment by chrissimpkins** [comment]
Added and available in the new CJK gallery
