### ISSUE TITLE
Update Iosevka fonts (1.0-beta9)

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#110]
from @be5invis in #55:

> ps. Recently Iosevka has changed a lot. Please update your images.

**Comment by be5invis** [comment]
Well, it is beta8 now and I made a slab here either.

**Comment by chrissimpkins** [comment]
trying to get to it this week.  If you submit a PR, I am happy to merge it.

**Comment by chrissimpkins** [comment]
@be5invis updated in the Codeface repository
