### ISSUE TITLE
Add Ricty Diminished

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#130]
https://github.com/yascentur/RictyDiminished

add to CJK gallery

cc: @mkasu @yascentur

**Comment by chrissimpkins** [comment]
@yascentur Per Google Translate on your README page in the repository, I gather that Ricty Diminished is SIL OFL v1.1 licensed and it is OK to redistribute the fonts in this repository.  Would it be possible for you to confirm this?

Thanks

**Comment by mkasu** [comment]
I checked the README page and can confirm that it is indeed SIL OFL 1.1 licensed to allow redistribution under OFL.

**Comment by chrissimpkins** [comment]
@mkasu Thank you!  Confirming that the translation was correct.  I will include it in the CJK gallery.  Your interest stimulated this gallery btw.  You can find an early (in development) version of it here:

https://github.com/chrissimpkins/codeface/blob/cjk/CJK.md

**Comment by mkasu** [comment]
@chrissimpkins Thanks a lot for your efforts and I'm sorry I've been quite silent recently. I'm regularly reading the other issue and start investing more time when I'm done with my current thesis. :)

**Comment by chrissimpkins** [comment]
@mkasu no worries at all!  Pitch in if and when you have time.  Just wanted to make sure that you were aware that it is there thanks to you!

**Comment by chrissimpkins** [comment]
@mkasu also added you to the contributors list with the dubious (awesome) title 'Curvacious Bezier' ;)

**Comment by mkasu** [comment]
@chrissimpkins  I love it ;)

**Comment by chrissimpkins** [comment]
This is now available in the CJK.md gallery in the `cjk` branch of the repository: 

https://github.com/chrissimpkins/codeface/blob/cjk/CJK.md 

We will merge this to the master branch soon!  We have a few more gallery specimens in the works.  Thanks for the suggestion @mkasu!

cc: @yascentur
