### ISSUE TITLE
Update Iosevka fonts

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#134]
@be5invis Belleve, I am going to have a difficult time keeping up with the pace of your font releases.  Do you mind poking me on major releases?

**Comment by be5invis** [comment]
@chrissimpkins Iosevka is pretty stable now. The current changes only affect uncommon glyphs like IPA characters or superscripts. So you can slow down unless I notify you manually about important upgrades.

**Comment by chrissimpkins** [comment]
@be5invis That sounds good.  Thanks Belleve

**Comment by chrissimpkins** [comment]
Updated to v1.7.1 and released

**Comment by be5invis** [comment]
@chrissimpkins Good. And I think you can include Iosevka Slab either.

**Comment by chrissimpkins** [comment]
Happy to.  Mind submitting fonts as a PR?

**Comment by be5invis** [comment]
@chrissimpkins Sure.
