### ISSUE TITLE
another online font tester

### ISSUE THREAD

**Issue by tomByrer** [chrissimpkins/codeface#141]
Interestingly, you just drag & drop fonts into it; no sever-based font files used.  Though if the fonts were on a CDN... (which I could help with)
https://github.com/impallari/Font-Testing-Page

**Comment by chrissimpkins** [comment]
Issue is that most don't release Web fonts and those that declare reserved font names (with SIL OFL and other OS licenses) don't permit you to call it by the reserved font name (when reserved) if you generate your own.  There is a pretty detailed discussion about this in the SIL OFL FAQ.  

The drag and drop approach is nice but requires user effort.  There isn't a great solution that covers a broad range of the typefaces in a Web application form.
