### ISSUE TITLE
Add Menlo/Meslo

### ISSUE THREAD

**Issue by aloisdg** [chrissimpkins/codeface#148]
- [Menlo](https://en.wikipedia.org/wiki/Menlo_%28typeface%29)
- [Meslo](https://github.com/andreberg/Meslo-Font)

**Comment by chrissimpkins** [comment]
Both great fonts!  [Meslo is already included](https://github.com/chrissimpkins/codeface#meslo-lg-m-dz) and Menlo is not licensed for redistribution from what I can gather (unfortunately).

**Comment by aloisdg** [comment]
Thank you for the fast answer.
