### ISSUE TITLE
Add Monaco

### ISSUE THREAD

**Issue by aloisdg** [chrissimpkins/codeface#149]
- [Monaco](https://en.wikipedia.org/wiki/Monaco_%28typeface%29)
- [install on linux](https://github.com/cstrap/monaco-font)

**Comment by chrissimpkins** [comment]
Another excellent font but also a system font on OS X and not licensed for redistribution.  

```
© 1990-2008 Apple Inc. © 1990-97 Type Solutions Inc. © 1990-97 The Font Bureau Inc.  TrueType outline design of Monaco typeface created by Kris Holmes and Charles Bigelow.
```
