### ISSUE TITLE
Include gallery images from Linux systems

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#15]
Need help from others to complete this.

**Comment by boblehest** [comment]
Do you just need people to look at the images and tell if they're ok or not?

**Comment by chrissimpkins** [comment]
many of the fonts render differently on the various platforms.  It would be helpful to know if there are dramatic differences for the fonts in the collection so that I can comment on it in a font specific readme file.  Ideally, we post additional images for those fonts

**Comment by boblehest** [comment]
If I'm not mistaken, it looks the your images is taken with a subpixel ordering of BGR, and mine uses RGB, and that's why it looks a bit blurry here.

**Comment by boblehest** [comment]
Edit: I deleted my previous comment about subpixel ordering, I got tricked by your bright colorscheme. :)

**Comment by chrissimpkins** [comment]
Spacegray for Sublime Text: https://kkga.github.io/spacegray/

**Comment by boblehest** [comment]
At first I assumed all pictures were JPEGs. FYI, every single image looks kinda weird to me. But it's really hard to tell what the issue is. For all I know, it's just the washed out colors playing a trick on my mind, making me believe that the quality is bad.

I'll see if I can find a similar color scheme for vim and compare, I don't have sublime text.

**Comment by chrissimpkins** [comment]
Do the images with the light grey background scheme look any better?

**Comment by boblehest** [comment]
Yes, they look better, but most of them appear to have some aliasing here.

Here's a comparison, Consola in gvim on top, and your image of Consola on the bottom:

http://i.imgur.com/9K26khA.png

I think the text on top looks a lot smoother.

**Comment by chrissimpkins** [comment]
Some reads that I found that seem to get to the heart of this issue.  OS X renders fonts differently than both Windows and Linux systems.  What looks normal to me, likely does look unusual to you.  OS X tends to have heavier glyphs with more antialiasing than you are used to seeing on either of the other platforms.

Atwood on Apple vs. Windows font rendering: 

* http://blog.codinghorror.com/font-rendering-respecting-the-pixel-grid/ 
* http://blog.codinghorror.com/whats-wrong-with-apples-font-rendering/

Joel Spolsky on the same issue: 

* http://www.joelonsoftware.com/items/2007/06/12.html

More discussion about the issue:

* http://damieng.com/blog/2007/06/13/font-rendering-philosophies-of-windows-and-mac-os-x

Mac vs Linux rendering: 

* http://arunoda.me/blog/font-rendering-mac-vs-ubunut.html

Disabling Mac default antialiasing:
* http://osxdaily.com/2010/02/18/change-font-smoothing-settings/  (apparently you can turn it off) 

They are relatively old articles, not sure how much has changed in newer OS X versions.

**Comment by chrissimpkins** [comment]
Attempting to address this issue with PR #49

**Comment by chrissimpkins** [comment]
See discussion in PR #49
