### ISSUE TITLE
Broken image previews in Nondistrib

### ISSUE THREAD

**Issue by dogancelik** [chrissimpkins/codeface#153]
The image previews are broken in https://github.com/chrissimpkins/codeface/blob/master/NONDISTRIB.md

**Comment by chrissimpkins** [comment]
Thank you! I didn't recognize this with the recent transition to an automated approach to the images.  Will fix it.

**Comment by chrissimpkins** [comment]
Fixed!  Thanks much for noting this problem.  I really appreciate it.  Added your name to the contributors list.

**Comment by dogancelik** [comment]
@chrissimpkins Thank you!
