### ISSUE TITLE
Cousine has lost its semi-colon

### ISSUE THREAD

**Issue by PhilipDaniels** [chrissimpkins/codeface#154]
The latest version of Cousine does not have a semi-colon.
Test environment: mintty under Cygwin.

I just setup a new laptop and installed all these Codeface fonts. Typing ';' in mintty with Cousine just prints a thin rectangular box. I have a PC with an older version of Cousine, so I copied it over to the new laptop and the semi-colon is back. I then re-installed Cousine from this pack, and the semi-colon is gone again (so it was not a one-off install problem).

**Comment by chrissimpkins** [comment]
Odd.  I will look into it.  Thanks for reporting it.

**Comment by chrissimpkins** [comment]
I just re-installed v1.020 of Cousine and confirmed that the semicolon is present in this set.  I will update the fonts this week.   Here is the v1.020 release of Cousine if you need it.

[cousine.zip](https://github.com/chrissimpkins/codeface/files/146390/cousine.zip)

Thanks again for noticing this.  I really appreciate it.

**Comment by PhilipDaniels** [comment]
You're welcome. Thanks for collating all this stuff.

On 25 February 2016 at 11:24, Chris Simpkins <notifications@github.com>
wrote:

> I just re-installed v1.020 of Cousine and confirmed that the semicolon is
> present in this set. I will update the fonts this week. Here is the v1.020
> release of Cousine if you need it.
>
> cousine.zip
> <https://github.com/chrissimpkins/codeface/files/146390/cousine.zip>
>
> Thanks again for noticing this. I really appreciate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrissimpkins/codeface/issues/154#issuecomment-188739081>
> .
>



-- 
Philip Daniels.

**Comment by chrissimpkins** [comment]
Fixed! Thanks much for noting this issue.  The new Cousine release is now available and all images have been updated.  Also added you to our contributors list.  ^5
