### ISSUE TITLE
+ Nimbus Mono

### ISSUE THREAD

**Issue by tomByrer** [chrissimpkins/codeface#155]
https://www.fontsquirrel.com/fonts/nimbus-mono
Need a PR?  Might be a few days/weeks.

**Comment by tomByrer** [comment]
Forgot; this has like 40 different versions; look at downloader on bottom:
http://larsenwork.com/monoid/
Might need a different approach...

**Comment by chrissimpkins** [comment]
Added! I am going to add a few others from one of the PR's and will push a new archive that includes the set of fonts.  Thanks for the recommendation!

For Monoid, Andreas wanted to point to his website for customization.  We are just releasing the default version here.
