### ISSUE TITLE
Idea: Categorize between coding fonts with ligatures and without and explain..

### ISSUE THREAD

**Issue by mpathy** [chrissimpkins/codeface#158]
There are fonts like Fira Code, Hasklig and so on, who do some other crazy stuff besides just being coding fonts..

They in fact create coding ligatures.

Use one of those fonts, type stuff like !== or => and so on and be stunned :)

But it doesnt work with all consoles..

Use the list from the Fira Code font github and link it here..

**Comment by chrissimpkins** [comment]
Added in PR #163
