### ISSUE TITLE
Colorscheme name?

### ISSUE THREAD

**Issue by dmitriyK1** [chrissimpkins/codeface#159]
Hi!
I'd like to know what is the dark colorscheme name that is used on sample screenshots?
Thanks in advance.

**Comment by chrissimpkins** [comment]
Thanks for asking! It is a custom scheme by David van Gemeren @burodepeper.

https://github.com/burodepeper/minimal-syntax-dark 

Check it out at that link.  I believe that he makes it available for the Atom editor.

**Comment by dmitriyK1** [comment]
Thanks! That's what I was looking for :)

**Comment by burodepeper** [comment]
@dmitriyK1 Enjoy!

**Comment by chrissimpkins** [comment]
@burodepeper :+1:

**Comment by cata0309** [comment]
What about the light syntax theme?

**Comment by chrissimpkins** [comment]
I believe that we are using the light version of @burodepeper theme that is available at https://github.com/burodepeper/minimal-syntax

**Comment by burodepeper** [comment]
That is correct!
