### ISSUE TITLE
Designate which typefaces have programming ligatures

### ISSUE THREAD

**Issue by KSuttle-cng** [chrissimpkins/codeface#162]
Possibly to augment: https://github.com/chrissimpkins/codeface/issues/119

https://www.hanselman.com/blog/MonospacedProgrammingFontsWithLigatures.aspx

![screen shot 2017-07-21 at 2 16 51 pm](https://user-images.githubusercontent.com/29458877/28476779-46536846-6e1f-11e7-8ed1-7c749bb88937.png)

**Comment by chrissimpkins** [comment]
I like that idea.  Habe a suggestion about how best to do so? Simple flag next to typeface name?

**Comment by KSuttle-cng** [comment]
Maybe group them together in the list, and/or include the ligatures in the font specimen? Might be tricky since they all don't have the same ligatures. However, maybe examples like the ones above could be used—ones that represent common programming character groupings.

**Comment by chrissimpkins** [comment]
Interested in contributing to this effort? We can definitely update the specimen across fonts to demonstrate examples of commonly used ligatures across all of the fonts.  Problem is, I don't know if our rendering approach will print the ligatures in the images.   If successful, would be a way for those who like ligatures to compare appearance / alignment issues across all fonts in the collection.

**Comment by KSuttle-cng** [comment]
Yeah for sure. What do you need?

**Comment by chrissimpkins** [comment]
Will check the specimen over the weekend.  My thought would be to add a single line of commonly used ligature combinations as the final line of the specimen.  Perhaps you could PR in the ligature glyph combinations that are the most commonly used/most important for comparison of fonts as that line in the specimen?

**Comment by kevinSuttle** [comment]
Sounds good!

**Comment by chrissimpkins** [comment]
Here is our main README page text specimen file that we use to build the specimen images.  

https://github.com/chrissimpkins/codeface/blob/master/samplecode/test-pattern.txt

Want to PR in one line in that file with what you view as most commonly used glyph combinations that are re-formatted as source code ligatures?  We can try to re-generate all of the images with our script and see if it accounts for the ligatures features code in the fonts that include it.  If not, we may be stuck for specimen display and an alternative would be a badge(?) next to the name of fonts that include ligatures.

**Comment by chrissimpkins** [comment]
I suppose the goal here would be to demonstrate breadth of support for ligatures that are used across programming languages rather than a purely language specific use situation if possible.

**Comment by kevinSuttle** [comment]
Cool. I'll take a look.

**Comment by kevinSuttle** [comment]
So, the "in one line" could prove an issue. 
Check out all the ligatures here: 

https://github.com/tonsky/FiraCode/blob/master/showcases/all_ligatures.png

I got to: 
```
-> --> ==> -> => <=< <=> >>- >>= <~> ~= != === !== && || >=<= <|| </> <!-- www && ?? !! i++ #### *** 0xFF := #! ;; 
```

and decided I should check with you first.

**Comment by chrissimpkins** [comment]
showcase of ligatures isn't primary objective of the gallery, just a snapshot that shows commonly used ones would be my thought.  let's stick with one line of what you feel are the best examples of broadly used ligatures.

**Comment by chrissimpkins** [comment]
Merged!  Includes badges for fonts that have ligature support. Thanks for contributing this @kevinSuttle!   You have been added to our contributors list and dubbed 'The Ligature'.

👍

**Comment by KSuttle-cng** [comment]
Wow thanks, Chris! Super happy to be a part. Thanks for opening this up. 

_- Kevin "The Ligature" Suttle_

**Comment by chrissimpkins** [comment]
:wink: thanks for your help to make it better!
