### ISSUE TITLE
Font Rendering in Screenshots

### ISSUE THREAD

**Issue by monolifed** [chrissimpkins/codeface#167]
I am using some of these font. They look better on linux than they do in those screenshots. I assume lcdfiltering is not used because they would looks different on different displays. But larger font rendered with hintfull might illustrate the fonts better.

**Comment by chrissimpkins** [comment]
We are using an automated rendering process with pango/cairo:

https://github.com/chrissimpkins/codeface/blob/master/scripts/render.py

Have thoughts about how to improve it?  Or transition to something completely new that still allows us to use the syntax highlighting?  I am open to changes if there are any thoughts out there.

**Comment by chrissimpkins** [comment]
I am not aware of an approach that would perform those tasks.  I suspect that there is a way to do it with another font renderer (or perhaps settings that improve the display with the current approach).  Let's leave this open to see if we get any feedback from others out there.
