### ISSUE TITLE
Wrong license for Liberation Mono?

### ISSUE THREAD

**Issue by brezniczky** [chrissimpkins/codeface#172]
Hi,

I had little time to double check on this, so I might be talking rubbish, but I suppose that the Open Fonts License 1.1 is the currently governing one for Liberation Mono.

What I found here seems like a GPL v2
https://github.com/chrissimpkins/codeface/blob/master/fonts/liberation-mono/license.txt

If I am correct, an adequate replacement could be 
https://github.com/liberationfonts/liberation-fonts/blob/master/LICENSE

so it's possibly a quick thing, but might affect other items in the liberation family.

As I found [Wikipedia](https://en.wikipedia.org/wiki/Liberation_fonts) might explain what's going on:

'License: 
SIL Open Font License (version 2 onwards)
GPL v2 with some exceptions (older versions)[1]'

Best,

Janos

**Comment by chrissimpkins** [comment]
Thank you very much for pointing this out Janos!  It looks like we have Liberation Mono v1.04 in this repository and it must have been under a different license.  It looks like the latest release is https://github.com/liberationfonts/liberation-fonts/releases/tag/2.1.1 which is under SIL OFL.

Let's update the fonts and license!

**Comment by chrissimpkins** [comment]
#173

**Comment by chrissimpkins** [comment]
Updated and merged. Thanks again!

**Comment by brezniczky** [comment]
Thank you very much for looking into it this quickly and responding, really helpful and much appreciated!

**Comment by chrissimpkins** [comment]
My pleasure.  Thanks Again!
