### ISSUE TITLE
Recommendation tool for font selection

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#25]
From reddit thread: https://www.reddit.com/r/programming/comments/39wz4l/hey_reddit_developers_what_is_your_favorite_text/cs7ufhy

> A recommendation tool of that calls out specific and useful character examples might be nice to see. Do you like this 'l' character or that one? or "here are pairs of confusing letters: 'Il' and 'O0'" - pick which pair you like the best..."

**Comment by larsenwork** [comment]
Personal preference but I'd say zooming in on examples can be a bit misleading and not really that relevant - I'd rather have a filterable preview of code examples. 

So the user can set a couple of criteria like: 
* Pixel font
* Semi-condensed
* Slashed zero
* Normal sized operators
* Haskell ligatures
* Supports all latin languages, cyrillic, greek

with live updates so only fonts meeting you criteria is shown.

**Comment by p8952** [comment]
You say in CONTRIBUTING.md:

```
I will generate the gallery image and take care of the rest.
```

Is this process automated? If so could it be put into the repo? It would be useful for generating images for use in a suggestion tool.

**Comment by chrissimpkins** [comment]
100% manual... I am generating images from the [samplecode directory](https://github.com/chrissimpkins/codeface/tree/master/samplecode) with a screenshot tool until I can find a better solution...

**Comment by larsenwork** [comment]
Why not just show the fonts on a webpage? It's what i did with monoid and feedback on actually having a live version instead of just images has been great.

**Comment by chrissimpkins** [comment]
It's a work in progress :)  The repository is 48 hours old...   I completely agree that is the next step.  Interested in helping with this?

**Comment by chrissimpkins** [comment]
Website/web app discussion is being routed to issue #25.  Copied this message there
