### ISSUE TITLE
Broaden and improve glyphs to assess legibility and compare differences between fonts

### ISSUE THREAD

**Issue by dvhh** [chrissimpkins/codeface#27]
I Would like to see the `0` (zero) char in the samples (as having a dotted or slashed zero would help choose the font ).

Showing one piece of code is fine, but the most common char should also be included
( like `a-z` `A-Z` `0-9` `/` `*` `-` `+` ... etc  )

Editor auto coloring is nice to look at, but does not help judge the font.

**Comment by chrissimpkins** [comment]
Multiple people made this request in the [Reddit thread](https://www.reddit.com/r/programming/comments/39wz4l/hey_reddit_developers_what_is_your_favorite_text/) today.  I received [a link to this text by Jeff Atwood](http://blog.codinghorror.com/is-your-ide-hot-or-not/) and may use it for high res images of each font. 

```
#region codinghorror.com
class Program : Object
{
  static int _I = 1;
  /// <summary>
  /// The quick brown fox jumps over the lazy dog
  /// THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG
  /// </summary>
  static void Main(string[] args)
  {
    Uri Illegal1Uri = new Uri("http://packmyboxwith/jugs.html?q=five-dozen&t=liquor");
    Regex OperatorRegex = new Regex(@"S#$", RegexOptions.IgnorePatternWhitespace);
    for (int O = 0; O < 123456789; O++)
    {
      _I += (O % 3) * ((O / 1) ^ 2) - 5;
      if (!OperatorRegex.IsMatch(Illegal1Uri.ToString()))
      {
        Console.WriteLine(Illegal1Uri);
      }
    }
  }
}
#endregion
```

A short test pattern similar to the one used on the Tamsyn font site would be helpful as well: 

![ss1-8x16r](https://cloud.githubusercontent.com/assets/4249591/8174754/a9a1dda6-13ae-11e5-9dd3-6b38a9b2c69e.png) 

Will definitely include these features.  Thanks much for the suggestion!

**Comment by chrissimpkins** [comment]
Added new test pattern images for all of the main gallery fonts.  Let me know what you think.

**Comment by dvhh** [comment]
This was what I was hoping for, thanks for the fix

**Comment by chrissimpkins** [comment]
Thanks again for the suggestion.
