### ISSUE TITLE
Suggestion: Choose a more appropriate code sample for the screenshots

### ISSUE THREAD

**Issue by curioustechizen** [chrissimpkins/codeface#31]
While choosing a font for coding, one of the most important factors to look for is how the font distinguishes between characters that resemble each other very closely. For example,

  - Is the lower-case letter `l` easily distinguishable from the number `1`?
  - Is the upper case letter `O` easily distinguishable from the number `0`? 

I'm sure there are more such examples. It would be nice if the screenshots chose code that makes it easy to spot this character of the font. For example, there could be variables named `l1` and `O0`.

**Comment by chrissimpkins** [comment]
Thank you! Definitely agree and am working on this.  This has already been reported in #27 .  I will close this issue.  Let me know what you think of the sample code in that issue. -C
