### ISSUE TITLE
Use 1Illinois instead of Illegal1

### ISSUE THREAD

**Issue by larsenwork** [chrissimpkins/codeface#34]
I find it to be even more "sensitive"

**Comment by chrissimpkins** [comment]
Thanks Andreas.  In the queue!

**Comment by larsenwork** [comment]
:+1:

**Comment by chrissimpkins** [comment]
I may be able to automate the generation of the gallery images with this new PR #49 .  If so, will make this change across all font types.

**Comment by chrissimpkins** [comment]
Added a different test pattern to each font
