### ISSUE TITLE
Add the other M+ fonts

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#4]
http://mplus-fonts.osdn.jp/mplus-outline-fonts/design/

**Comment by larsenwork** [comment]
Would be cool if the screenshots for fonts with multiple options were slowly changing GIFs

**Comment by chrissimpkins** [comment]
This is a great idea for the website.  I really like the Monoid site alot.  You did a great job on it.  Would you be interested in helping to design one for all of the fonts in this collection?

**Comment by larsenwork** [comment]
Yep, I'm very busy the next couple of weeks though but I'd love to help brainstorm/conceptualise how it can be executed as I love the idea behind it but I don't have the time to do any coding legwork right now.

I'd recommend you set it all up using github pages so read a bit about that if you're not familiar with how it works, buy a domain name and host the CDN at cloudflare. 

Use modern web technologies and don't bother about legacy support - your visitors will not be browsing using IE8 and will have no problem switching a browser.

I saw this the other day and thought it looked great: http://tympanus.net/codrops/2015/06/16/filterable-product-grid/ (should be easy to change so you can make multiple selections)

**Comment by chrissimpkins** [comment]
Sounds great.  I have multiple GH pages sites (for software documentation) and a paid Cloudflare account so we will be all set from that standpoint.  I will need advice/help on the frontend design if you'd be willing to pitch in.   Web design is definitely not my forté.

Like the concept in that link.  That would work well with this project.  Will get a repository set up for the website and be in touch once I do a bit more research into the best way to present it and am prepared to discuss a site scaffold in more detail.  Thanks much.

**Comment by larsenwork** [comment]
:+1:

**Comment by larsenwork** [comment]
You may already know this but it's really easy to loop through content with jekyll e.g. https://github.com/larsenwork/animalnoteheads/blob/gh-pages/_includes/tables.html#L13

**Comment by chrissimpkins** [comment]
wasn't aware of this.  thanks much! will take a look

**Comment by larsenwork** [comment]
So what we could do is to make every font a blog entry with a lot of metadata so it's filterable (and that meta data can always be expand/adjust down the line).

This way you only have to write the demo text once and just for-loop through all fonts.

Categories could be use for major groupings like bitmap, outline

**Comment by chrissimpkins** [comment]
Is it as simple as just adding new meta data fields to the header section of new posts?

**Comment by larsenwork** [comment]
Ja

**Comment by larsenwork** [comment]
could use tags for meta - they are defined in the frontmatter http://jekyllrb.com/docs/frontmatter/

**Comment by chrissimpkins** [comment]
Web site/web app discussion now in #25.  This issue will be closed when the font is added to the repository

**Comment by chrissimpkins** [comment]
added
