### ISSUE TITLE
Add Fixedsys Excelsior font

### ISSUE THREAD

**Issue by bkaradzic** [chrissimpkins/codeface#44]
http://www.fixedsysexcelsior.com/

**Comment by chrissimpkins** [comment]
Thank you!  Any idea of the license associated with this font?

**Comment by bkaradzic** [comment]
Fixedsys Excelsior is free software and appears to have been released by its 
    author into the public domain.

From: https://en.wikipedia.org/wiki/Fixedsys_Excelsior

**Comment by chrissimpkins** [comment]
thanks.  didn't think to look in Wikipedia.  I checked the font site.

**Comment by chrissimpkins** [comment]
Fixedsys Excelsior is now included in the repository.  Thanks much!
