### ISSUE TITLE
Indicate if a font is scalable or bitmap and specific sizes for bitmap fonts

### ISSUE THREAD

**Issue by squires** [chrissimpkins/codeface#46]
People may prefer bitmap or scalable fonts, or it's just nice to have that information for comparison.

**Comment by chrissimpkins** [comment]
that's a good suggestion. I did add readme files to each bitmap repo that indicates the size that were rendered for gallery images, but this would be helpful

**Comment by chrissimpkins** [comment]
I think that I am going to add a small indicator next to the font name to address this issue.  In the works.

**Comment by chrissimpkins** [comment]
There is a [new bitmap gallery](https://github.com/chrissimpkins/codeface/blob/master/BITMAP.md) that will be distinct from the main gallery so that users are aware of this issue.  I will link it to the main gallery this weekend. Thank you very much for the suggestion!
