### ISSUE TITLE
Non-libre fonts

### ISSUE THREAD

**Issue by raphaelbastide** [chrissimpkins/codeface#60]
Some font licenses are not open source, how to deal with it? How to quickly make the difference with F/LOSS typefaces? I am not even sure non open source (freeware) can be hosted on GitHub. What do you think?

**Comment by chrissimpkins** [comment]
> Some font licenses are not open source, how to deal with it?

I am only hosting font binaries with licenses/EULA that permit redistribution of the font.  I created a [separate gallery](https://github.com/chrissimpkins/codeface/blob/master/NONDISTRIB.md) for typefaces that are free, but explicitly specify that redistribution of font binaries is not permitted in their EULA.  In this case, I simply point to the proper download site for the file(s).  

In cases, where the license was not explicit I contacted the copyright holder before distributing the font here (for example with the Mensch font).  

> How to quickly make the difference with F/LOSS typefaces?

Can you expand on this?  I am not following you.

> I am not even sure non open source (freeware) can be hosted on GitHub. 

I completely agree with this comment.  If you find a typeface where this is in question, please let me know.  I have done my best to identify the correct license for everything that is included in the repository.  I do not intend to divert people away from the original distribution source, but rather to provide a simple way for developers to compare fonts and easily access them.  If copyright holders prefer not to have a font hosted here despite the license that they applied to their work, I am more than willing to remove it.

**Comment by raphaelbastide** [comment]
Free / Libre Open Source fonts can be modified and redistributed. Some of the font on your list can’t. [Ex 1](https://github.com/chrissimpkins/codeface/blob/master/fonts/monofur/monof_tt.txt) [ex 2](https://github.com/chrissimpkins/codeface/blob/master/fonts/pro-font-windows/license.txt), there are maybe more. You will find more details on [this page](https://help.github.com/articles/open-source-licensing/).

**Comment by chrissimpkins** [comment]
Got it. The intent was not to create a repository entirely of modifiable font types (free as in do anything with it) as it is not targeted to designers as substrate for new fonts.  It was to provide a wide selection of free (as in free for use) types that can be used in development environments by software engineers/developers who spend a significant amount of time face to face with source code and the common character types, idioms, spacing structure that it contains. 

I think that this does raise a great point about the need for better organization and display of the fonts.  I recognize that the markdown/Github README format is not ideal but it does provide a good starting point to create something better that clearly indicates the font source, associated license, and font data/properties.  This is the next big step for the project.  There are a few of us who are looking into the best web presentation design to make that happen.  If this is something that you are interested in helping with we would love to involve you.  Let me know.

**Comment by raphaelbastide** [comment]
I understand your point and your project makes totally sense, but you can’t exclude possible hackers (that wants to modify, just like me) from your target. You can instead alert / inform about the license. I think this is part of your future plans, so I think we agree on the importance of a clear documentation :)

**Comment by chrissimpkins** [comment]
Couldn't agree more!  

I recognize my (code) developer-centric view of the repository as well from this discussion.  I really hadn't given much consideration to the fact that this could be a resource for designers who would like to develop new fonts based upon the ones available here.  All important points.

**Comment by chrissimpkins** [comment]
...which just gave me an idea.  For those fonts that do carry licenses that permit modification, would it be helpful to distribute Font Forge sfd font source files (or another source type) to facilitate the font design effort?

**Comment by raphaelbastide** [comment]
Yes, and / or [UFO](http://unifiedfontobject.org/) if you can find it, because is used by a lot of font editor now. [This](https://github.com/raphaelbastide/Whois-mono/) is an example of font repository with an UFO source.

**Comment by chrissimpkins** [comment]
You didn't mention that you had fonts! Interested in putting them in the repository?  Happy to help get the word out about them.

What software do you use for development?  From the limited reading that I have done after your message above, it sounds as though the FontForge UFO source export has some issues.  Came across forums discussing [Robofont](http://doc.robofont.com/) and UFO's.

**Comment by chrissimpkins** [comment]
An admirer included your Whois Mono font as a PR today.  It's now in the repository.

**Comment by raphaelbastide** [comment]
Wonderful! I’m glad it is part of the list :)

**Comment by chrissimpkins** [comment]
Great font!  Can I contact you off GH about a font editor that handles UFO source?  Are you on Twitter?

**Comment by raphaelbastide** [comment]
Yes, [@raphaelbastide](https://twitter.com/raphaelbastide)

**Comment by chrissimpkins** [comment]
sent! thanks
