### ISSUE TITLE
Add italics to screenshots

### ISSUE THREAD

**Issue by teogeos** [chrissimpkins/codeface#64]
It would be nice to see some words in the code samples be in italics to compare them since many text editor themes use them.

**Comment by chrissimpkins** [comment]
Not all of the fonts support italics.  In some cases, it is the editor creating an oblique version of the font in those syntax highlighters.  

What editor and theme are you using?  I'd be happy to take a look.

**Comment by teogeos** [comment]
Indeed, you could put italics only for those that support them.

The default sublime text theme uses italics as you can see in their home page demo:
http://www.sublimetext.com/

Here are some themes for jetbrains IDEs with italics:
http://www.ideacolorthemes.org/themes/7/
http://www.ideacolorthemes.org/themes/100/
http://www.ideacolorthemes.org/themes/104/

**Comment by chrissimpkins** [comment]
Thanks much.  I have been playing around with  type specimen sheets for these fonts that will include italics/oblique versions when available.  Let me see how the web fonts approximate the desktop versions.  It would be nice to avoid a new set of images for each typeface given the size of the list.  Do you feel that it is important to see these variants in the context of the syntax highlighting or is plain text display of each version sufficient?

**Comment by teogeos** [comment]
To me it would probably be important to see them in the context of syntax highlighting since those pictures give me a much better idea of whether I like a font or not. But you might want to ask other people for their opinions on this matter.

**Comment by chrissimpkins** [comment]
Let me see what I can do.  Thanks much for your feedback.

**Comment by tomByrer** [comment]
> Not all of the fonts support italics. In some cases, it is the editor creating an oblique version of the font in those syntax highlighters.

It would be good to see how the OS creates italics with a font that is missing it.  Different platforms (OS, browser, etc) could render italics differently, but it would still be of interest.
OTOH, usually only comments a few key words are in Italics.

**Comment by chrissimpkins** [comment]
I am considering a standardized type specimen sheet for each typeface that will look something like this: 

http://chrissimpkins.github.io/Hack/font-specimen.html 

This will display the oblique/italic glyphs when available and I can add a block that displays oblique/italics x font size similar to the display for the regular font type.  It will not provide a syntax highlighting view with real code.  I suppose that we could add a comment in the C code block that is shown in the gallery and replace the syntax highlighter with one that includes italics for comments.

**Comment by chrissimpkins** [comment]
See #119 for the new proposed gallery image set.  This will include syntax highlighters that use italics for comment blocks.

**Comment by tomByrer** [comment]
I'm wondering if there should be an entire codeblock in italics?  Common practice to "comment out" some code while developing/testing.  Since my prior comment (sorry), I have had trouble before reading commented out code.

**Comment by chrissimpkins** [comment]
See the new images for Anonymous Pro in the `image-scripting` branch:

https://github.com/chrissimpkins/codeface/tree/image-scripting

I've included a comment line that will be rendered in oblique.  We could consider adding a pangram such as the one that @be5invis suggested in order to provide an example of (most of) the ASCII characters in oblique.

```
float Fox.quick(h){ is_brown && it_jumps_over(doges.lazy) }
```

**Comment by teogeos** [comment]
Very nice! Thank you for the efforts you put on this issue. As for myself, the comments in italics are exactly what I needed.

**Comment by chrissimpkins** [comment]
Hope to have these out soon!  Thanks for letting me know.

**Comment by chrissimpkins** [comment]
Oblique/italics are now available in the main gallery images.
