### ISSUE TITLE
Add Camingo Code Font

### ISSUE THREAD

**Issue by m90** [chrissimpkins/codeface#83]
Free font available at: http://www.myfonts.com/fonts/jan-fromm/camingo-code/

**Comment by chrissimpkins** [comment]
thanks for sharing this typeface.  I'll look into the licensing and include it in the collection.

**Comment by chrissimpkins** [comment]
License does permit redistribution of the font: http://www.myfonts.com/viewlicense?lid=1781 

Thanks again!

**Comment by chrissimpkins** [comment]
Added the font and included you on the contributors list.  Beautiful font.  Thanks much for suggesting it!
