### ISSUE TITLE
Add Input Mono Font

### ISSUE THREAD

**Issue by aardappel** [chrissimpkins/codeface#86]
http://input.fontbureau.com/

Very customizable programmer font that looks gorgeous.

**Comment by chrissimpkins** [comment]
Thanks for the suggestion Wouter.  Unfortunately they do not allow redistribution of their font binaries so it is listed over on this gallery: 

https://github.com/chrissimpkins/codeface/blob/master/NONDISTRIB.md 

I definitely agree, it's a highly customizable, excellent choice!
