### ISSUE TITLE
Add Courier Prime Code 

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#88]
http://quoteunquoteapps.com/courierprime/  

The slashed zero version link is at the bottom of the page.  SIL Open Font license

**Comment by chrissimpkins** [comment]
Install error on OS X systems.  Will not add until this is fixed.

**Comment by peteyy** [comment]
Works well on OSX (El Capitan) and also on Linux (Manjaro latest) it this is the only font I'm missing please consider adding it to the collection. :+1:

**Comment by chrissimpkins** [comment]
great to hear that they addressed this issue.  will include it. thanks for letting me know.

**Comment by chrissimpkins** [comment]
Added this to the main gallery + repository and added your name to the contributors list.  Thanks much for looking into this and for the recommendation!
